# Generated by Django 2.2.3 on 2019-08-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='path',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='data',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='size',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='type',
            field=models.TextField(blank=True),
        ),
    ]
